#!/usr/bin/python
#  -*- coding: utf-8 -*-
# author:  <yao62995@gmail.com>

import os
import tempfile
import paramiko


class SSHConnection(object):
    """Connects and logs into the specified hostname.
    Arguments that are not given are guessed from the environment."""

    def __init__(self,
                 host,
                 username=None,
                 private_key=None,
                 password=None,
                 port=22,
                 ):
        self._sftp_live = False
        self._sftp = None
        if not username:
            username = os.environ['LOGNAME']

        # Log to a temporary file.
        temp_log = tempfile.mkstemp('.txt', 'ssh-')[1]
        paramiko.util.log_to_file(temp_log)

        # Begin the SSH transport.
        self._transport = paramiko.Transport((host, port))
        self._tranport_live = True
        # Authenticate the transport.
        if password:
            # Using Password.
            self._transport.connect(username=username, password=password)
        else:
            # Use Private Key generated by ssh-key-gen
            if not private_key:
                # Try to use default key.
                if os.path.exists(os.path.expanduser('~/.ssh/id_rsa')):
                    private_key = '~/.ssh/id_rsa'
                elif os.path.exists(os.path.expanduser('~/.ssh/id_dsa')):
                    private_key = '~/.ssh/id_dsa'
                else:
                    raise TypeError, "You have not specified a password or key."

            private_key_file = os.path.expanduser(private_key)
            rsa_key = paramiko.RSAKey.from_private_key_file(private_key_file)
            self._transport.connect(username=username, pkey=rsa_key)

    def _sftp_connect(self):
        """Establish the SFTP connection."""
        if not self._sftp_live:
            self._sftp = paramiko.SFTPClient.from_transport(self._transport)
            self._sftp_live = True

    def get(self, remote_path, local_path=None):
        """Copies a file between the remote host and the local host."""
        if not local_path:
            local_path = os.path.split(remote_path)[1]
        self._sftp_connect()
        self._sftp.get(remote_path, local_path)

    def put(self, local_path, remote_path=None):
        """Copies a file between the local host and the remote host."""
        if not remote_path:
            remote_path = os.path.split(local_path)[1]
        self._sftp_connect()
        self._sftp.put(local_path, remote_path)

    def execute(self, command):
        """Execute the given commands on a remote machine."""
        channel = self._transport.open_session()
        channel.exec_command(command)
        output = channel.makefile('rb', -1).readlines()
        if output:
            return output
        else:
            return channel.makefile_stderr('rb', -1).readlines()

    def close(self):
        """Closes the connection and cleans up."""
        # Close SFTP Connection.
        if self._sftp_live:
            self._sftp.close()
            self._sftp_live = False
        # Close the SSH Transport.
        if self._tranport_live:
            self._transport.close()
            self._tranport_live = False

    def __del__(self):
        """Attempt to clean up if not explicitly closed."""
        self.close()


def main():
    """Little test when called directly."""
    # Set these to your own details.
    myssh = SSHConnection('dpl03.example.com', username="yaojian-xy")
    myssh.put('ssh.py', "/home/yaojian-xy/see.py")
    # print myssh.execute("ls /home/yaojian-xy/")
    myssh.close()


# start the ball rolling.
if __name__ == "__main__":
    main()
